//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Teams.Apps.FAQPlusPlus.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Teams.Apps.FAQPlusPlus.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App feedback.
        /// </summary>
        public static string AppFeedbackText {
            get {
                return ResourceManager.GetString("AppFeedbackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzmana Sor.
        /// </summary>
        public static string AskAnExpertButtonText {
            get {
                return ResourceManager.GetString("AskAnExpertButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzmana Sorun.
        /// </summary>
        public static string AskAnExpertDisplayText {
            get {
                return ResourceManager.GetString("AskAnExpertDisplayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorunuzla alakalı paylaşmak istediğiniz detayları buraya yazın (maks 500 karakter).
        /// </summary>
        public static string AskAnExpertPlaceholderText {
            get {
                return ResourceManager.GetString("AskAnExpertPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bir uzman size 1:1 mesaj ile dönecektir..
        /// </summary>
        public static string AskAnExpertSubheaderText {
            get {
                return ResourceManager.GetString("AskAnExpertSubheaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzmana Sor.
        /// </summary>
        public static string AskAnExpertText1 {
            get {
                return ResourceManager.GetString("AskAnExpertText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...Eğer soruna uygun cevabı veremezsem... Seni bir uzmana yönlendireceğim..
        /// </summary>
        public static string AskAnExpertText2 {
            get {
                return ResourceManager.GetString("AskAnExpertText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorunuz cevaplanmak üzere bir uzmana atandı. İlgili uzman size bir mesaj ile ulaşacaktır..
        /// </summary>
        public static string AssignedTicketUserNotification {
            get {
                return ResourceManager.GetString("AssignedTicketUserNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned to {0}.
        /// </summary>
        public static string AssignedToStatusValue {
            get {
                return ResourceManager.GetString("AssignedToStatusValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birine atandı.
        /// </summary>
        public static string AssignedUserNotificationStatus {
            get {
                return ResourceManager.GetString("AssignedUserNotificationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign to me.
        /// </summary>
        public static string AssignStatusTitle {
            get {
                return ResourceManager.GetString("AssignStatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bana ata.
        /// </summary>
        public static string AssignToMeActionChoiceTitle {
            get {
                return ResourceManager.GetString("AssignToMeActionChoiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change status.
        /// </summary>
        public static string ChangeStatusButtonText {
            get {
                return ResourceManager.GetString("ChangeStatusButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ile konuş.
        /// </summary>
        public static string ChatTextButton {
            get {
                return ResourceManager.GetString("ChatTextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapat.
        /// </summary>
        public static string CloseActionChoiceTitle {
            get {
                return ResourceManager.GetString("CloseActionChoiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed by {0}.
        /// </summary>
        public static string ClosedByStatusValue {
            get {
                return ResourceManager.GetString("ClosedByStatusValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapatıldı: .
        /// </summary>
        public static string ClosedFactTitle {
            get {
                return ResourceManager.GetString("ClosedFactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İsteğiniz sonuçlandırılmıştır. Eğer hala desteğe ihtiyaç duyuyorsanız bir uzmana sor&apos;a tıklayın..
        /// </summary>
        public static string ClosedTicketUserNotification {
            get {
                return ResourceManager.GetString("ClosedTicketUserNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapatıldı.
        /// </summary>
        public static string ClosedUserNotificationStatus {
            get {
                return ResourceManager.GetString("ClosedUserNotificationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseStatusText {
            get {
                return ResourceManager.GetString("CloseStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseStatusTitle {
            get {
                return ResourceManager.GetString("CloseStatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soruna uygun bir cevap bulamadım. Sorunu bir uzmana yönlendirmemi ister misin?.
        /// </summary>
        public static string CustomMessage {
            get {
                return ResourceManager.GetString("CustomMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oluşturuldu: .
        /// </summary>
        public static string DateCreatedDisplayFactTitle {
            get {
                return ResourceManager.GetString("DateCreatedDisplayFactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tanıtım:.
        /// </summary>
        public static string DescriptionFact {
            get {
                return ResourceManager.GetString("DescriptionFact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tanım.
        /// </summary>
        public static string DescriptionText {
            get {
                return ResourceManager.GetString("DescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **{0}** geri bildirim paylaştı..
        /// </summary>
        public static string FeedbackAlertText {
            get {
                return ResourceManager.GetString("FeedbackAlertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geri bildiriminizi ve detaylarını giriniz (maks 500 karakter).
        /// </summary>
        public static string FeedbackDescriptionPlaceholderText {
            get {
                return ResourceManager.GetString("FeedbackDescriptionPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share app feedback.
        /// </summary>
        public static string FeedbackHeaderText {
            get {
                return ResourceManager.GetString("FeedbackHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geri bildirim (Zorunlu).
        /// </summary>
        public static string FeedbackRatingRequired {
            get {
                return ResourceManager.GetString("FeedbackRatingRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzman ekibine benim hakkımda geri bildirim verip, daha iyi çalışmamı sağlayabilirsin..
        /// </summary>
        public static string FeedbackText1 {
            get {
                return ResourceManager.GetString("FeedbackText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soru Sor.
        /// </summary>
        public static string FunctionCardText1 {
            get {
                return ResourceManager.GetString("FunctionCardText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bana aşağıdaki yazı ekranından mesaj atarak soru sorabilirsin. Soruna cevap vermek için elimden geleni yapacağım ...  .
        /// </summary>
        public static string FunctionCardText2 {
            get {
                return ResourceManager.GetString("FunctionCardText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to original thread.
        /// </summary>
        public static string GoToOriginalThreadButtonText {
            get {
                return ResourceManager.GetString("GoToOriginalThreadButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yararlı buldum.
        /// </summary>
        public static string HelpfulRatingText {
            get {
                return ResourceManager.GetString("HelpfulRatingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knowledge base entry:.
        /// </summary>
        public static string KBEntryFactTitle {
            get {
                return ResourceManager.GetString("KBEntryFactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soru girmek zorunludur..
        /// </summary>
        public static string MandatoryTitleFieldText {
            get {
                return ResourceManager.GetString("MandatoryTitleFieldText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biraz daha geliştirilmeli.
        /// </summary>
        public static string NeedsImprovementRatingText {
            get {
                return ResourceManager.GetString("NeedsImprovementRatingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string NonApplicableString {
            get {
                return ResourceManager.GetString("NonApplicableString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have access to this app. Please contact your IT admin..
        /// </summary>
        public static string NonSMEErrorText {
            get {
                return ResourceManager.GetString("NonSMEErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yararlı değil.
        /// </summary>
        public static string NotHelpfulRatingText {
            get {
                return ResourceManager.GetString("NotHelpfulRatingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorunu ilgili uzmanlarla paylaştım. Sana direkt mesaj ile cevap verecekler..
        /// </summary>
        public static string NotificationCardContent {
            get {
                return ResourceManager.GetString("NotificationCardContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string NotificationCardTitleText {
            get {
                return ResourceManager.GetString("NotificationCardTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unassigned.
        /// </summary>
        public static string OpenStatusTitle {
            get {
                return ResourceManager.GetString("OpenStatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorulan soru:.
        /// </summary>
        public static string QuestionAskedFactTitle {
            get {
                return ResourceManager.GetString("QuestionAskedFactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **{0}** destek talebinde bulunuyor..
        /// </summary>
        public static string QuestionForExpertSubHeaderText {
            get {
                return ResourceManager.GetString("QuestionForExpertSubHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question for expert.
        /// </summary>
        public static string QuestionForExpertText {
            get {
                return ResourceManager.GetString("QuestionForExpertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is what I have found for your request.
        /// </summary>
        public static string QuestionLineText {
            get {
                return ResourceManager.GetString("QuestionLineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listeden bir seçenek seçin.
        /// </summary>
        public static string RatingMandatoryText {
            get {
                return ResourceManager.GetString("RatingMandatoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Değerlendirme.
        /// </summary>
        public static string RatingTitle {
            get {
                return ResourceManager.GetString("RatingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reassign to me.
        /// </summary>
        public static string ReassignStatusTitle {
            get {
                return ResourceManager.GetString("ReassignStatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticketı yeniden aç.
        /// </summary>
        public static string ReopenActionChoiceTitle {
            get {
                return ResourceManager.GetString("ReopenActionChoiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeniden aç ve bana ata.
        /// </summary>
        public static string ReopenAssignToMeActionChoiceTitle {
            get {
                return ResourceManager.GetString("ReopenAssignToMeActionChoiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzmana sorduğunuz soru yeniden değerlendiriliyor. Bir uzman size direkt mesajla ulaşacaktır..
        /// </summary>
        public static string ReopenedTicketUserNotification {
            get {
                return ResourceManager.GetString("ReopenedTicketUserNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulduğum yanıt şu şekilde:.
        /// </summary>
        public static string ResponseHeaderText {
            get {
                return ResourceManager.GetString("ResponseHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter feedback for above result.
        /// </summary>
        public static string Resultsfeedbackdetails {
            get {
                return ResourceManager.GetString("Resultsfeedbackdetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yanıt geri bildirimi..
        /// </summary>
        public static string ResultsFeedbackText {
            get {
                return ResourceManager.GetString("ResultsFeedbackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geri bildirim paylaş.
        /// </summary>
        public static string ShareFeedbackButtonText {
            get {
                return ResourceManager.GetString("ShareFeedbackButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geri Bildirim Verin.
        /// </summary>
        public static string ShareFeedbackDisplayText {
            get {
                return ResourceManager.GetString("ShareFeedbackDisplayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uygulama geri bildirimi.
        /// </summary>
        public static string ShareFeedbackTitleText {
            get {
                return ResourceManager.GetString("ShareFeedbackTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorunuzu buraya giriniz (Maks. 50 karakter).
        /// </summary>
        public static string ShowCardTitleText {
            get {
                return ResourceManager.GetString("ShowCardTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu istek birine atandı. Atanan kişi: {0}..
        /// </summary>
        public static string SMEAssignedStatus {
            get {
                return ResourceManager.GetString("SMEAssignedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everyone there is a new request coming in, please see the details below:.
        /// </summary>
        public static string SMEAttentionText {
            get {
                return ResourceManager.GetString("SMEAttentionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu istek kapatıldı. Kapatan: {0}..
        /// </summary>
        public static string SMEClosedStatus {
            get {
                return ResourceManager.GetString("SMEClosedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geri bildirim.
        /// </summary>
        public static string SMEFeedbackHeaderText {
            get {
                return ResourceManager.GetString("SMEFeedbackHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu istek kimseye atanmadı. Son güncelleyen: {0}. .
        /// </summary>
        public static string SMEOpenedStatus {
            get {
                return ResourceManager.GetString("SMEOpenedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atandı -&gt; {0}.
        /// </summary>
        public static string SMETicketAssignedStatus {
            get {
                return ResourceManager.GetString("SMETicketAssignedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapatıldı.
        /// </summary>
        public static string SMETicketClosedStatus {
            get {
                return ResourceManager.GetString("SMETicketClosedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Henüz birine atanmadı.
        /// </summary>
        public static string SMETicketUnassignedStatus {
            get {
                return ResourceManager.GetString("SMETicketUnassignedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RE: {0}.
        /// </summary>
        public static string SMEUserChatMessage {
            get {
                return ResourceManager.GetString("SMEUserChatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durum: .
        /// </summary>
        public static string StatusFactTitle {
            get {
                return ResourceManager.GetString("StatusFactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönder.
        /// </summary>
        public static string SubmitButtonText {
            get {
                return ResourceManager.GetString("SubmitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzman ekip turu.
        /// </summary>
        public static string TakeATeamTourButtonText {
            get {
                return ResourceManager.GetString("TakeATeamTourButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kısa Bir Gezinti.
        /// </summary>
        public static string TakeATourButtonText {
            get {
                return ResourceManager.GetString("TakeATourButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcıyla mesajlaş butonuna basarak konuşmayı direkt konuşmayı başlatabilirsiniz..
        /// </summary>
        public static string TeamChatContent {
            get {
                return ResourceManager.GetString("TeamChatContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son kullanıcılarla 1&apos;e 1 görüşme başlatma.
        /// </summary>
        public static string TeamChatHeaderText {
            get {
                return ResourceManager.GetString("TeamChatHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merhaba, Henüz uzman ekip içerisinde özel komut mesajlarını destekleyemiyorum. Yeteneklerm hakkında bilgi almak için ekip turuna bakabilirsin..
        /// </summary>
        public static string TeamCustomMessage {
            get {
                return ResourceManager.GetString("TeamCustomMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcılarınız size ihtiyaç duyguduğunda buraya mesaj atacağım..
        /// </summary>
        public static string TeamNotificationContent {
            get {
                return ResourceManager.GetString("TeamNotificationContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son kullanıcılardan bildirim alma.
        /// </summary>
        public static string TeamNotificationHeaderText {
            get {
                return ResourceManager.GetString("TeamNotificationHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelen soruları birine atayarak ya da kapatıldı olarak işaretleyerek durumunu takip edebilirsiniz. .
        /// </summary>
        public static string TeamTicketSystemContent {
            get {
                return ResourceManager.GetString("TeamTicketSystemContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelen uzman sorularını yönetme.
        /// </summary>
        public static string TeamTicketSystemHeaderText {
            get {
                return ResourceManager.GetString("TeamTicketSystemHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geri bildirim için teşekkürler! Uzmanlarla paylaştım. Bu benim gelişmemi ve daha iyi çalışmamı sağlayacak..
        /// </summary>
        public static string ThankYouTextContent {
            get {
                return ResourceManager.GetString("ThankYouTextContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soru başlığı:.
        /// </summary>
        public static string TitleFact {
            get {
                return ResourceManager.GetString("TitleFact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soru (zorunlu).
        /// </summary>
        public static string TitleRequiredText {
            get {
                return ResourceManager.GetString("TitleRequiredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atamayı kaldır.
        /// </summary>
        public static string UnassignActionChoiceTitle {
            get {
                return ResourceManager.GetString("UnassignActionChoiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unassigned.
        /// </summary>
        public static string UnassignedStatusValue {
            get {
                return ResourceManager.GetString("UnassignedStatusValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Henüz birine atanmadı.
        /// </summary>
        public static string UnassignedUserNotificationStatus {
            get {
                return ResourceManager.GetString("UnassignedUserNotificationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unassign.
        /// </summary>
        public static string UnassignStatusTitle {
            get {
                return ResourceManager.GetString("UnassignStatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verilen cevabı gör.
        /// </summary>
        public static string ViewArticleButtonText {
            get {
                return ResourceManager.GetString("ViewArticleButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merhaba Ekip,  
        ///Ben Robot. Son kullanıcıların sorularını cevaplamak ve sizle iletişimini sağlamak için buradayım..
        /// </summary>
        public static string WelcomeTeamCardContent {
            get {
                return ResourceManager.GetString("WelcomeTeamCardContent", resourceCulture);
            }
        }
    }
}
